<a href="https://colab.research.google.com/github/Dhruvin3103/sem6/blob/master/ml/emp_left_log_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [167]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix

In [168]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/7_logistic_reg/Exercise/HR_comma_sep.csv")
df.tail(5)
df['left'].value_counts()

0    11428
1     3571
Name: left, dtype: int64

In [169]:
X = df[['number_project','time_spend_company']]
y =df["left"].values
X = X.values
X

array([[2, 3],
       [5, 6],
       [7, 4],
       ...,
       [2, 3],
       [6, 4],
       [2, 3]])

In [170]:
# this is cell carries out the code to reduce dataset so that number of records for both class 0 and 1 are equal

import numpy as np

# Assuming X and Y are your input features and labels
# Replace X and Y with your actual dataset

# Find the indices of records for each class
indices_class_0 = np.where(y == 0)[0]
indices_class_1 = np.where(y == 1)[0]

# Determine the number of records to keep for each class (equal to the size of the minority class)
num_records_to_keep = min(len(indices_class_0), len(indices_class_1))

# Randomly sample a subset of records for each class
selected_indices_class_0 = np.random.choice(indices_class_0, size=num_records_to_keep, replace=False)
selected_indices_class_1 = np.random.choice(indices_class_1, size=num_records_to_keep, replace=False)

# Combine the selected indices for both classes
selected_indices = np.concatenate([selected_indices_class_0, selected_indices_class_1])

# Extract the subset of the dataset based on the selected indices
X = X[selected_indices]
y = y[selected_indices]

# y.value_counts()

In [171]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,y,train_size=0.7,random_state=42)
Y_train

array([0, 1, 0, ..., 1, 1, 0])

In [172]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def initialize_params(dim):
    return np.zeros((dim, 1)), 0

def propagate(X, Y, w, b):
    m = X.shape[1]

    # Forward propagation
    A = sigmoid(np.dot(w.T, X) + b)
    epsilon = 1e-15  # Small epsilon value to avoid log(0)
    cost = -1/m * np.sum(Y * np.log(A + epsilon) + (1 - Y) * np.log(1 - A + epsilon))

    # Backward propagation
    dw = 1/m * np.dot(X, (A - Y).T)
    db = 1/m * np.sum(A - Y)

    return dw, db, cost

def optimize(X, Y, w, b, num_iterations, learning_rate):
    costs = []

    for i in range(num_iterations):
        dw, db, cost = propagate(X, Y, w, b)

        # Gradient descent
        w -= learning_rate * dw
        b -= learning_rate * db

        if i % 100 == 0:
            costs.append(cost)

    return w, b, costs

def predict(X, w, b):
    A = sigmoid(np.dot(w.T, X) + b)
    return (A > 0.5).astype(int)

def accuracy(Y_true, Y_pred):
    return np.mean(Y_true == Y_pred)

def confusion_matrix(Y_true, Y_pred):
    tp = np.sum((Y_true == 1) & (Y_pred == 1))
    tn = np.sum((Y_true == 0) & (Y_pred == 0))
    fp = np.sum((Y_true == 0) & (Y_pred == 1))
    fn = np.sum((Y_true == 1) & (Y_pred == 0))

    return np.array([[tp, fp], [fn, tn]])

# Assuming X_train, Y_train, X_test, Y_test are your training and testing sets
X_train = X_train.T
Y_train = Y_train.reshape(1, -1)

X_test = X_test.T
Y_test = Y_test.reshape(1, -1)

# Initialize parameters
w, b = initialize_params(X_train.shape[0])

# Optimize the parameters using gradient descent
w, b, costs = optimize(X_train, Y_train, w, b, num_iterations=5000, learning_rate=0.01)

Y_test_pred = predict(X_test, w, b)

acc_test = accuracy(Y_test.flatten(), Y_test_pred.flatten())
conf_mat_test = confusion_matrix(Y_test.flatten(), Y_test_pred.flatten())

print("\nTesting Accuracy:", acc_test)
print("Testing Confusion Matrix:")
print(conf_mat_test)


Testing Accuracy: 0.7162855809612693
Testing Confusion Matrix:
[[799 366]
 [242 736]]
